# Selecting Region of Interest

This chapter provides an overview about the Python scripts used to create a polygonal region of interest and mask for images contained in folders. Before beginning this section, ensure that all image files are properly named. 

`interactive_ROI_app.py` is the script used to create a region of interest and mask for images within a folder. Function descriptions and a visual aid for this section can be found here [TODO: put link to function descriptions and visual aid]

## Packages and Path Configuration

This section will detail the package imports necessary to use this script, as well as instruction on setting the path to the image folder on a users local computer.

### Import Necessary Packages

Load in all necessary packages. In the making and testing of our script, we have found that the "`Qt5Agg`" backend works best for Windows system while the "`MacOSX`" backend works best for Apple. These backends allow us to work interactively with the python plotting library `matplotlib`. For more information, visit `matplotlib`'s official website.[TODO: footnote for matplotlib backends] If already imported, duplicates are not created.

```{python load-python-packages-roi, eval = FALSE}
import re
import matplotlib as mpl
import os.path
import pandas as pd
from PIL import Image

mpl.use('Qt5Agg')  # backend
import cv2
from roipoly import RoiPoly
import glob2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
from collections import OrderedDict
from matplotlib.path import Path as MplPath
```

### Configure Folder Path

Our script denotes the file path to a folder and stores it in a variable `folder_path`. Change the example path to the path of the folder for which to operate on. We then use the `.glob` function of the `glob` package to store the file path for each image into the variable `image_folder`. After setting the filepath, the user is ready for interactive polygon selection.

```{python configure-folder-path, eval = FALSE}
# Sample Image Local Folder (eg. Images)
folder_path = r"C:\Users\Path\To\Images"

# Read paths to all the images into image_folder list
image_folder = glob2.glob(folder_path + "/*")
```

Using the path to each image from image_folder, an object for each image is created using the ImageFile class. Within this class are functions that extract the time stamp and an array of RGB values for each image. Additionaly, the water year for each image is derived from its timestamp, as is a sliced array version for each image for faster plotting. These objects are appended to image_file_list which is then sorted by water years.[TODO: maybe include link to visual]

``` {python image_file_list, eval = FALSE}
TODO: put in
code for appending to image_file_list, sorting image_file_list
```

## Interaction

This section details instruction for creating a polygonal region of interest and mask for a folder of images.

### Instruction

`RoiPoly`[TODO: put in footnotes the orignal repo] is the python module from which our mouse click events are handled. The functions within this script allow the user to create an ROI by drawing a polygon with mouse clicks. A point is drawn by left clicking, from which a line is bounded to, extending to the user cursor. By left-clicking again, a new point is created and the line becomes static. A new line is again shown from the last point to the user cursor. To complete a figure, the user simply right or double clicks, bounding the last selected point to the first. The polygon created within the image is the region of interest.

[TODO: put in image of first roi being created]


### Region of Interest and Masking

### Output

### Button Background